module.exports = {
  arrOverallJiraCollection: [],
  arrTagReportSolutionCollection: [],
  componentTagsCreated: [],
  solutionTagsCreated: [],
  arrComponents: [],
  arrExt: [],
  arrSVNExternalsPreviousSolutionTag: [],
  arrSVNExternalsCurrentSolutionTag: [],
  arrPreviousExternals: [],
  arrMissingCollection: [],
  arrSwitchUpdateCollection: [],
  arrSVNUpdatedCollection: [],
  arrSVNPotentialUpdateCollection: [],
  arrFlywayUpdatedCollection: [],
  arrCompareSpecificUpdateCollection: [],
  arrDeploymentCheckCollection: [],
  arrTagReportCollection: [],
  arrUnlinkedFolderCollection: [],
  bDone: false,
  profile: {},
  oAppContext: {},
  app: '',
  arrInternalsFilter: [],
  workingCopyFolder: '',
  tagReportArray: [],
  oSVNInfo: {},
  currentSolution: '',
  oSolution: {},
  beInformedRunning: false,
  timestampStart: '', // new Date().toISOString().replaceAll('T', '').replaceAll('-', '').replaceAll(':', '').substring(0, 14)
  exitCode: 0,
  prettySVNUsername: 'Anonymous',
  startingTime: Date.now(),
  endingTime: Date.now(),
  hasMinDataArgument: false,
};
